name: Form
version: 1.8.0
description: Form Plugin to render user forms for Flextype.
icon: fas fa-check-circle
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/form
documentation: https://github.com/flextype-plugins/form
changelog: https://github.com/flextype-plugins/form/blob/master/CHANGELOG.md
bugs: https://github.com/flextype-plugins/form/issues
keywords: form, fieldsets
license: MIT

dependencies:
  flextype: 0.9.14
  twig: '>=1.0.0'
  jquery: '>=1.0.0'
