name: Form
version: 1.0.0
description: Form Plugin to manage user forms for Flextype.
icon: fas fa-check-circle
author:
  name: Sergey Romanenko
  email: support@flextype.org
  url: http://flextype.org
homepage: https://github.com/flextype-plugins/form
bugs: https://github.com/flextype-plugins/form/issues
license: MIT
