name: Form
version: 1.11.0
description: Form Plugin to render user forms for Flextype.
icon:
  name: card-list
  set: bootstrap
author:
  name: Sergey Romanenko
  email: sergey.romanenko@flextype.org
  url: https://flextype.org
homepage: https://github.com/flextype-plugins/form
documentation: https://github.com/flextype-plugins/form
changelog: https://github.com/flextype-plugins/form/blob/master/CHANGELOG.md
bugs: https://github.com/flextype-plugins/form/issues
license: MIT

dependencies:
  flextype: 0.9.16
  twig: '>=2.0.0'
  jquery: '>=1.0.0'
